## Top 50 Male runners

I've used the request library to get the HTML version of a website. The website contained links that had information about each of the runners. Using the `BeautifulSoup` library I was able to parse information for each runner. This was done by a for loop retrieving the links for each runner and requesting that web page with the request library. The request library gave the HTML containing their specific information about themselves. Every time the for loop ran it added the needed information to a dictionary. After the for loop was finished, I created a Data Frame for the top 50 males with the Pandas Library. There was also a 2 second delay between each request to each runnerâ€™s site.

In [1]:
#importing request, BeaitifulSoup, sleep and Pandas
import requests
from bs4 import BeautifulSoup
from time import sleep
import pandas as pd

In [2]:
#requesting url containing information
r = requests.get("https://results.chicagomarathon.com/well-known/2019/?page=1&content=well-known&event=MAR&lang=EN_CAP&num_results=50&pid=list&search%5Bsex%5D=M&search%5Bage_class%5D=%25").text

In [3]:
#using BeaitfulSoup to get parse HTML file
soup = BeautifulSoup(r)
names= soup.find_all('h4')
#dictoray that'll contain runners infromation
directory = []
#forloop runs 50 times so it gets 50 runners
for i in range(0,50):
    listing = {}
    #finding link of the runner then requesting it with url
    a = names[i].find("a")['href']
    name_site = "https://results.chicagomarathon.com/well-known/2019/"+a
    r = requests.get(name_site).text
    #2 second delay
    for i in range(2):
        sleep(i)
    
    #gets all information needed and adding to dictionary
    soup = BeautifulSoup(r)
    info= soup.find_all('div', class_="detail-box box-general")
    splits= soup.find_all('div', class_="table-responsive")
    
    listing["Name CTZ"] = info[0].find('td',class_="f-__fullname last").get_text()
    listing["Age Group"] = info[0].find('td',class_="f-age_class last").get_text()
    listing["Bib Number"] = info[0].find('td',class_="f-start_no_text last").get_text()
    listing["Age"] = info[0].find('td',class_="f-age last").get_text()
    listing["City, State"] = info[0].find('td',class_="f-__city_state last").get_text()
    
    
    Fivek = splits[0].find_all('tr',class_="f-time_05 split")
    Tenk = splits[0].find_all('tr',class_="list-highlight f-time_10 split")
    Fifteenk = splits[0].find_all('tr',class_="f-time_15 split")
    twentyk = splits[0].find_all('tr',class_="list-highlight f-time_20 split")
    Half = splits[0].find_all('tr',class_="f-time_52 split")
    twentyfive = splits[0].find_all('tr',class_="list-highlight f-time_25 split")
    thirty = splits[0].find_all('tr',class_="f-time_30 split")
    thirtyfive = splits[0].find_all('tr',class_="list-highlight f-time_35 split")
    fourty = splits[0].find_all('tr',class_="f-time_40 split")
    finish = splits[0].find_all('tr',class_="list-highlight f-time_finish_netto highlight")
    
    
    
    
    listing["05K"] = Fivek[0].find('td',class_='time').get_text()
    listing["10K"] = Tenk[0].find('td',class_='time').get_text()
    listing['15K'] = Fifteenk[0].find('td',class_='time').get_text()
    listing["20K"] = twentyk[0].find('td',class_='time').get_text()
    listing["Half"] = Half[0].find('td',class_='time').get_text()
    listing['25K'] = twentyfive[0].find('td',class_='time').get_text()
    listing['30K'] = thirty[0].find('td',class_='time').get_text()
    listing['35k'] = thirtyfive[0].find('td',class_='time').get_text()
    listing['40k'] = fourty[0].find('td',class_='time').get_text()
    listing['Finish'] = finish[0].find('td',class_='time').get_text()
    
    directory.append(listing)

In [4]:
#creating dataframe with dictoranry
df = pd.DataFrame(directory)
df

,Name CTZ,Age Group,Bib Number,Age,"City, State",05K,10K,15K,20K,Half,25K,30K,35k,40k,Finish
0,"Cherono, Lawrence (KEN)",30-34,4,31,Chepkoilel,00:14:45,00:29:28,00:44:11,00:59:01,01:02:15,01:13:57,01:28:59,01:43:54,01:59:10,02:05:45
1,"Debela, Dejene (ETH)",20-24,38,24,West Chester,00:14:45,00:29:29,00:44:12,00:59:02,01:02:16,01:13:56,01:28:59,01:43:53,01:59:08,02:05:46
2,"Mengstu, Asefa (ETH)",30-34,5,31,Addis Ababa,00:14:46,00:29:29,00:44:12,00:59:02,01:02:15,01:13:55,01:28:59,01:43:53,01:59:08,02:05:48
3,"Karoki, Bedan (KEN)",25-29,9,29,Mbuyu,00:14:45,00:29:27,00:44:10,00:59:02,01:02:15,01:13:54,01:28:59,01:43:53,01:59:09,02:05:53
4,"Abdi, Bashir (BEL)",30-34,10,30,Nijmegen,00:14:47,00:29:30,00:44:23,00:59:32,01:02:54,01:14:53,01:30:22,01:45:15,01:59:53,02:06:14
5,"Tura, Seifu (ETH)",20-24,39,22,Addis Abeba,00:14:46,00:29:29,00:44:12,00:59:02,01:02:15,01:13:56,01:28:59,01:43:53,02:00:13,02:08:35
6,"Chumba, Dickson (KEN)",30-34,6,32,Kipngoror,00:14:45,00:29:27,00:44:11,00:59:01,01:02:14,01:13:55,01:28:58,01:44:27,02:01:05,02:09:11
7,"Farah, Mo (GBR)",35-39,1,36,Teddington,00:14:47,00:29:29,00:44:23,00:59:32,01:02:54,01:14:54,01:30:30,01:46:23,02:02:28,02:09:58
8,"Riley, Jacob (USA)",30-34,16,30,Boulder,00:15:33,00:30:59,00:46:30,01:01:59,01:05:24,01:17:33,01:33:17,01:48:44,02:04:02,02:10:36
9,"Mock, Jerrell (USA)",20-24,36,24,Fort Collins,00:15:33,00:30:58,00:46:30,01:01:59,01:05:25,01:17:32,01:33:17,01:48:44,02:04:02,02:10:37
10,"Stinson, Parker (USA)",25-29,23,27,Boulder,00:15:32,00:30:58,00:46:30,01:01:59,01:05:25,01:17:32,01:33:17,01:48:44,02:04:03,02:10:53
11,"Bumbalough, Andrew (USA)",30-34,20,32,Concord,00:15:32,00:30:58,00:46:29,01:01:59,01:05:25,01:17:33,01:33:19,01:48:48,02:04:03,02:10:56
12,"Oishi, Minato (JPN)",30-34,11,31,Hamamatsu,00:15:25,00:30:59,00:46:29,01:01:59,01:05:24,01:17:34,01:33:19,01:48:45,02:04:15,02:11:02
13,"Mcdonald, Matthew (USA)",25-29,21,26,Atlanta,00:15:34,00:31:00,00:46:31,01:02:01,01:05:25,01:17:33,01:33:18,01:48:45,02:04:09,02:11:10
14,"Smith, Scott (USA)",20-24,15,23,Flagstaff,00:15:33,00:30:59,00:46:29,01:01:58,01:05:25,01:17:32,01:33:17,01:48:46,02:04:13,02:11:14
15,"Gregg, Brendan (USA)",30-34,17,30,Davis,00:15:33,00:30:58,00:46:31,01:01:59,01:05:25,01:17:34,01:33:18,01:48:55,02:04:40,02:11:38
16,"Droddy, Noah (USA)",25-29,25,29,Boulder,00:15:32,00:30:59,00:46:30,01:02:00,01:05:25,01:17:34,01:33:18,01:48:54,02:04:44,02:11:42
17,"Given, Wilkerson (USA)",25-29,24,28,Atlanta,00:15:33,00:30:59,00:46:31,01:02:01,01:05:26,01:17:34,01:33:19,01:48:55,02:04:40,02:11:44
18,"Estrada, Diego (USA)",25-29,19,29,Flagstaff,00:15:34,00:31:00,00:46:31,01:02:01,01:05:26,01:17:35,01:33:18,01:48:55,02:04:46,02:11:54
19,"Hayakawa, Tsubasa (JPN)",25-29,14,29,Tahara,00:15:26,00:30:58,00:46:30,01:01:59,01:05:25,01:17:33,01:33:18,01:48:55,02:04:52,02:12:25
20,"Takeuchi, Ryoma (JPN)",25-29,12,27,Matsudo Chiba,00:15:33,00:30:59,00:46:30,01:01:59,01:05:25,01:17:34,01:33:19,01:48:57,02:05:19,02:12:26
21,"Shrader, Brian (USA)",25-29,18,28,Brighton,00:15:34,00:31:08,00:46:49,01:02:28,01:05:54,01:18:19,01:34:05,01:50:04,02:06:16,02:13:27
22,"Monroe, Alex (USA)",25-29,34,27,Longmont,00:15:34,00:31:00,00:46:30,01:02:00,01:05:26,01:17:35,01:33:19,01:48:58,02:05:57,02:14:15
23,"Kremske, Daniel (USA)",30-34,31,30,Chicago,00:15:46,00:31:53,00:47:57,01:04:11,01:07:44,01:20:26,01:36:15,01:52:07,02:07:56,02:14:53
24,"Milam, Willie (USA)",25-29,33,27,Louisville,00:15:56,00:31:43,00:47:26,01:03:22,01:06:51,01:19:27,01:35:20,01:51:18,02:07:31,02:14:54
25,"Mickow, Colin (USA)",25-29,572,29,Naperville,00:16:09,00:32:15,00:48:22,01:04:26,01:07:57,01:20:25,01:36:15,01:52:07,02:07:55,02:14:55
26,"Peterson, Alan (USA)",25-29,28,27,Chicago,00:16:09,00:32:15,00:48:22,01:04:26,01:07:57,01:20:26,01:36:15,01:52:07,02:07:55,02:14:56
27,"Mazaheri, Bijan (USA)",25-29,706,25,Pasadena,00:15:58,00:32:13,00:48:23,01:04:27,01:07:57,01:20:26,01:36:16,01:52:07,02:08:02,02:15:26
28,"Havel, Kevin (USA)",25-29,488,29,Chicago,00:16:09,00:32:17,00:48:24,01:04:43,01:08:16,01:21:01,01:37:19,01:53:09,02:08:37,02:15:37
29,"Lennon, Daniel (USA)",25-29,544,25,Albany,00:15:39,00:31:16,00:46:56,01:02:40,01:06:07,01:18:23,01:34:05,01:50:12,02:08:02,02:16:08
30,"Sanabria-Diaz, Alvaro (CRC)",25-29,634,29,Kearney,00:15:57,00:32:13,00:48:25,01:04:44,01:08:16,01:21:02,01:37:20,01:53:26,02:09:31,02:16:29
31,"Ortiz Perez, Daniel (MEX)",35-39,592,35,Torreon,00:16:09,00:32:09,00:47:57,01:04:11,01:07:44,01:20:26,01:36:15,01:52:28,02:09:12,02:16:50
32,"Root, Ryan (USA)",25-29,26,27,Iowa City,00:16:18,00:32:45,00:49:08,01:05:27,01:09:02,01:21:55,01:38:04,01:54:11,02:10:10,02:16:59
33,"Wiley, Turner (USA)",25-29,687,26,Seattle,00:16:36,00:32:45,00:49:08,01:05:26,01:09:01,01:21:54,01:38:04,01:54:11,02:10:10,02:17:00
34,"Herzig, Matthew (USA)",20-24,495,24,Philadelphia,00:15:55,00:32:06,00:48:15,01:04:27,01:07:57,01:20:28,01:36:27,01:52:56,02:09:36,02:17:02
35,"Peloquin, Conner (USA)",25-29,598,27,Seattle,00:16:36,00:32:46,00:49:08,01:05:26,01:09:01,01:21:54,01:38:04,01:54:12,02:10:10,02:17:02
36,"Neff, Jackson (USA)",25-29,30,27,Chicago,00:16:09,00:32:17,00:48:25,01:04:43,01:08:16,01:21:01,01:37:19,01:53:32,02:10:01,02:17:21
37,"Cross, Will (USA)",25-29,432,26,Upland,â€“,00:32:45,00:49:08,01:05:26,01:09:02,01:21:55,01:38:04,01:54:12,02:10:21,02:17:33
38,"Hansen, Kevin (USA)",35-39,484,35,Lk Forest Pk,00:16:36,00:32:46,00:49:08,01:05:27,01:09:01,01:21:55,01:38:04,01:54:23,02:10:59,02:18:25
39,"May, Christopher (USA)",25-29,564,25,Elmhurst,00:16:16,00:32:45,00:49:08,01:05:27,01:09:02,01:21:54,01:38:04,01:54:12,02:10:45,02:18:34
40,"Medina, Oscar (MEX)",25-29,568,27,Chicago,00:16:10,00:32:17,00:48:26,01:04:47,01:08:22,01:21:28,01:37:54,01:54:23,02:11:25,02:18:45
41,"Campbell, Patrick (USA)",20-24,407,24,Madison,00:15:54,00:31:53,00:47:57,01:04:11,01:07:44,01:20:28,01:36:48,01:53:35,02:10:58,02:18:51
42,"Lustgarten, Brett (USA)",25-29,32,29,Carol Stream,00:16:10,00:32:16,00:48:23,01:04:26,01:07:57,01:20:31,01:37:00,01:54:01,02:11:23,02:18:59
43,"Smith, Ryan (USA)",20-24,651,24,Berkeley,00:16:09,00:32:21,00:48:26,01:04:54,01:08:25,01:21:12,01:37:38,01:54:18,02:11:14,02:19:22
44,"Gade, Noah (USA)",20-24,465,24,Stillwater,00:16:09,00:32:17,00:48:25,01:04:43,01:08:16,01:21:01,01:37:20,01:54:02,02:11:46,02:19:50
45,"Bang, Eric (CAN)",25-29,370,29,Oakville,00:16:09,00:32:17,00:48:26,01:04:47,01:08:22,01:21:30,01:38:16,01:55:14,02:12:21,02:19:56
46,"Eaton, Michael (USA)",30-34,29,32,Seattle,00:16:36,00:32:46,00:49:08,01:05:26,01:09:02,01:21:55,01:38:05,01:54:22,02:11:37,02:19:58
47,"Thomas, Jason (USA)",25-29,665,25,Urbandale,00:16:37,00:33:08,00:49:34,01:06:15,01:09:53,01:22:49,01:39:31,01:56:12,02:13:04,02:20:28
48,"Nally, Daniel (USA)",30-34,580,34,Littleton,00:16:38,00:33:05,00:49:34,01:06:15,01:09:53,01:22:48,01:39:11,01:55:56,02:13:07,02:20:38
49,"Craighead, Daniel (USA)",25-29,430,29,Lafayette,00:16:29,00:33:00,00:49:23,01:05:46,01:09:22,01:22:23,01:39:18,01:56:10,02:13:36,02:21:15